DATAS SEGMENT
    DATA1 DW 0F865H
    DATA2 DW 123CH  
DATAS ENDS

ESEG SEGMENT
	SUM DW 2 DUP(?)
ESEG ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,ES:ESEG
START:
    MOV AX,DATAS
    MOV DS,AX
    MOV AX,ESEG
    MOV ES,AX
    MOV DI,OFFSET SUM
    MOV AX,DATA1
    ADD AX,DATA2
    MOV ES:[DI],AX
    MOV AH,4CH
    INT 21H
CODES ENDS
    END START
